//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

DEFINE_GUID(CLSID_CSample, 0x0002d0d0, 0xd15e, 0xa5ed, 0xba, 0x11, 0x13, 0x55, 0x0f, 0xf1, 0xc1, 0xa1);
